# Generated by Django 5.2.7 on 2025-11-01 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name="pointhistory",
            name="challenge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="point_histories",
                to="challenges.challenge",
            ),
        ),
        migrations.AddField(
            model_name="pointhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="point_histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["email"], name="accounts_pr_email_08cbb0_idx"),
        ),
        migrations.AddIndex(
            model_name="pointhistory",
            index=models.Index(
                fields=["user", "-occurred_at"], name="accounts_po_user_id_c64d39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointhistory",
            index=models.Index(fields=["type"], name="accounts_po_type_02ecdd_idx"),
        ),
        migrations.AddIndex(
            model_name="pointhistory",
            index=models.Index(
                fields=["challenge"], name="accounts_po_challen_8ae445_idx"
            ),
        ),
    ]
