# Generated by Django 5.2.7 on 2025-11-01 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "challenges_category",
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, default="", max_length=200)),
                ("cover_image", models.URLField(blank=True, default="")),
                ("entry_fee", models.PositiveIntegerField(default=0)),
                ("duration_weeks", models.PositiveIntegerField(default=1)),
                (
                    "freq_type",
                    models.CharField(
                        choices=[
                            ("매일", "매일"),
                            ("평일", "평일"),
                            ("주말", "주말"),
                            ("주 N일", "주 N일"),
                        ],
                        default="매일",
                        max_length=10,
                    ),
                ),
                ("freq_n_days", models.PositiveIntegerField(blank=True, null=True)),
                ("ai_condition_text", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("active", "active"),
                            ("ended", "ended"),
                            ("canceled", "canceled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("member_limit", models.PositiveIntegerField(default=6)),
                ("member_count_cache", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenges",
                        to="challenges.challengecategory",
                    ),
                ),
            ],
            options={
                "db_table": "challenges_challenge",
            },
        ),
        migrations.CreateModel(
            name="ChallengeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "owner"), ("member", "member")],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("success_rate", models.FloatField(blank=True, null=True)),
                ("final_points_awarded", models.IntegerField(blank=True, null=True)),
                ("final_rank", models.IntegerField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "challenges_challenge_member",
            },
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(fields=["status"], name="challenges__status_076365_idx"),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["-start_date"], name="challenges__start_d_6af7f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["-end_date"], name="challenges__end_dat_1e534f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="challengemember",
            index=models.Index(
                fields=["challenge", "user"], name="challenges__challen_435485_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="challengemember",
            unique_together={("challenge", "user")},
        ),
    ]
