# Generated by Django 5.2.6 on 2025-11-01 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "challenges_category",
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, default="", max_length=200)),
                ("cover_image", models.URLField(blank=True, default="")),
                ("entry_fee", models.PositiveIntegerField(default=0)),
                ("duration_weeks", models.PositiveIntegerField(default=1)),
                (
                    "freq_type",
                    models.CharField(
                        choices=[
                            ("매일", "매일"),
                            ("평일", "평일"),
                            ("주말", "주말"),
                            ("주 N일", "주 N일"),
                        ],
                        default="매일",
                        max_length=10,
                    ),
                ),
                ("freq_n_days", models.PositiveIntegerField(blank=True, null=True)),
                ("ai_condition_text", models.TextField(blank=True, default="")),
                (
                    "settle_method",
                    models.CharField(
                        choices=[("equal", "equal"), ("performance", "performance")],
                        default="equal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("active", "active"),
                            ("ended", "ended"),
                            ("canceled", "canceled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("member_limit", models.PositiveIntegerField(default=6)),
                ("member_count_cache", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenges",
                        to="challenges.challengecategory",
                    ),
                ),
            ],
            options={
                "db_table": "challenges_challenge",
            },
        ),
        migrations.CreateModel(
            name="ChallengeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "owner"), ("member", "member")],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("success_rate", models.FloatField(blank=True, null=True)),
                ("final_points_awarded", models.IntegerField(blank=True, null=True)),
                ("final_rank", models.IntegerField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "challenges_challenge_member",
            },
        ),
        migrations.CreateModel(
            name="CompleteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="complete_images/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("approved", "승인"),
                            ("rejected", "거절"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complete_images",
                        to="challenges.challengemember",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complete_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "challenges_complete_image",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complete_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="challenges.completeimage",
                    ),
                ),
            ],
            options={
                "db_table": "challenges_comment",
            },
        ),
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_codes",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "db_table": "challenges_invite_code",
            },
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(fields=["status"], name="challenges__status_076365_idx"),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["-start_date"], name="challenges__start_d_6af7f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["-end_date"], name="challenges__end_dat_1e534f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="challengemember",
            index=models.Index(
                fields=["challenge", "user"], name="challenges__challen_435485_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="challengemember",
            unique_together={("challenge", "user")},
        ),
        migrations.AddIndex(
            model_name="completeimage",
            index=models.Index(fields=["status"], name="challenges__status_44d13c_idx"),
        ),
        migrations.AddIndex(
            model_name="completeimage",
            index=models.Index(
                fields=["-created_at"], name="challenges__created_f28fab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["complete_image"], name="challenges__complet_6c5571_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitecode",
            index=models.Index(fields=["code"], name="challenges__code_b6a1bc_idx"),
        ),
        migrations.AddIndex(
            model_name="invitecode",
            index=models.Index(
                fields=["expires_at"], name="challenges__expires_2d2e6e_idx"
            ),
        ),
    ]
