# Generated by Django 5.2.7 on 2025-11-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="challenge",
            old_name="ai_condition_text",
            new_name="ai_condition",
        ),
        migrations.AlterField(
            model_name="challenge",
            name="settle_method",
            field=models.IntegerField(
                choices=[
                    (1, "성공자끼리 1/N 균등 분배"),
                    (2, "성공률 비례 분배"),
                    (3, "성공자 환급 + 잔여 1/N 분배"),
                    (4, "실패자 참가비 기부"),
                ],
                default=1,
            ),
        ),
    ]
