# Generated by Django 5.2.7 on 2025-11-01 15:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompleteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="challenges/%Y/%m/%d/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("approved", "승인"),
                            ("rejected", "거절"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("proof_date", models.DateField(blank=True, null=True)),
                ("comment_cnt", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("expire_at", models.DateTimeField()),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="challengemember",
            name="challenges__challen_435485_idx",
        ),
        migrations.RenameField(
            model_name="challengemember",
            old_name="challenge",
            new_name="challenge_id",
        ),
        migrations.RenameField(
            model_name="challengemember",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AlterUniqueTogether(
            name="challengemember",
            unique_together={("challenge_id", "user_id")},
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="subtitle",
        ),
        migrations.AddField(
            model_name="challenge",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="settlement_method",
            field=models.CharField(
                choices=[
                    ("EQUAL", "균등 분배"),
                    ("PROPORTIONAL", "기여 비례"),
                    ("WINNER_TAKES_ALL", "승자 독식"),
                    ("CUSTOM", "사용자 정의"),
                ],
                default="EQUAL",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="duration_weeks",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="entry_fee",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="freq_n_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="freq_type",
            field=models.CharField(
                choices=[
                    ("DAILY", "매일"),
                    ("WEEKDAYS", "주중(월~금)"),
                    ("WEEKENDS", "주말(토~일)"),
                    ("N_DAYS_PER_WEEK", "주당 N회"),
                ],
                default="DAILY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="member_limit",
            field=models.PositiveIntegerField(
                default=6, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "초안"),
                    ("active", "진행 중"),
                    ("ended", "종료"),
                    ("canceled", "취소됨"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="challengecategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="challengemember",
            name="final_rank",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="challengemember",
            name="role",
            field=models.CharField(
                choices=[("owner", "개설자"), ("member", "참여자")],
                default="member",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="challengemember",
            name="success_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="challengemember",
            index=models.Index(
                fields=["challenge_id", "user_id"],
                name="challenges__challen_74621f_idx",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="challenge_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="challenges.challenge",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="completeimage",
            name="challenge_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complete_images",
                to="challenges.challenge",
            ),
        ),
        migrations.AddField(
            model_name="completeimage",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complete_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="image_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="challenges.completeimage",
            ),
        ),
        migrations.AddField(
            model_name="invitecode",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invite_codes",
                to="challenges.challenge",
            ),
        ),
    ]
