# Generated by Django 5.2.7 on 2025-11-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="x_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="y_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
