# Generated by Django 5.2.7 on 2025-11-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_comment_x_ratio_comment_y_ratio"),
        ("challenges", "0002_rename_ai_condition_text_challenge_ai_condition_and_more"),
    ]

    operations = []
