# Generated by Django 5.2.7 on 2025-11-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0003_merge_20251103_0209"),
        ("challenges", "0003_merge_20251103_0413"),
    ]

    operations = []
