# Generated by Django 5.2.7 on 2025-11-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0004_merge_20251103_0746"),
        ("challenges", "0004_merge_20251105_0437"),
    ]

    operations = []
