# Generated by Django 5.2.7 on 2025-11-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0005_merge_20251107_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="completeimage",
            name="review_reasons",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="completeimage",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
