# Generated by Django 5.2.7 on 2025-11-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0006_completeimage_review_reasons_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="completeimage",
            name="file_sha1",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="completeimage",
            name="flagged_duplicate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="completeimage",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completeimage",
            name="phash",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="completeimage",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
