# Generated by Django 5.2.7 on 2025-11-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0007_completeimage_file_sha1_and_more"),
        ("challenges", "0008_fix_and_seed_categories"),
    ]

    operations = []
