# Generated by Django 5.2.7 on 2025-11-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0009_merge_20251110_2139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="challenge_covers/"
            ),
        ),
    ]
