# Generated by Django 5.2.7 on 2025-11-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0010_alter_challenge_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="completeimage",
            name="converted_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="complete_images/converted/"
            ),
        ),
    ]
