# Generated by Django 5.2.7 on 2025-11-01 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "settlement_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("total_pool_point", models.IntegerField(blank=True, null=True)),
                (
                    "method",
                    models.IntegerField(
                        choices=[
                            (1, "성공자끼리 1/N 균등 분배"),
                            (2, "성공률 비례 분배"),
                            (3, "성공자 환급 + 잔여 1/N 분배"),
                            (4, "실패자 참가비 기부"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "예정"),
                            ("processing", "진행중"),
                            ("ready", "완료(수령 대기)"),
                            ("paid", "지급 완료"),
                        ],
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "db_table": "settlements_settlement",
            },
        ),
        migrations.CreateModel(
            name="SettlementDetail",
            fields=[
                ("detail_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reward_point", models.IntegerField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_details",
                        to="challenges.challengemember",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="settlements.settlement",
                    ),
                ),
            ],
            options={
                "db_table": "settlements_settlement_detail",
            },
        ),
        migrations.AddIndex(
            model_name="settlement",
            index=models.Index(
                fields=["challenge"], name="settlements_challen_65ab51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="settlement",
            index=models.Index(fields=["status"], name="settlements_status_83e9c8_idx"),
        ),
        migrations.AddIndex(
            model_name="settlement",
            index=models.Index(
                fields=["-scheduled_at"], name="settlements_schedul_feb39a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="settlementdetail",
            index=models.Index(
                fields=["settlement"], name="settlements_settlem_0056b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="settlementdetail",
            index=models.Index(
                fields=["challenge_member"], name="settlements_challen_1737d9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementdetail",
            constraint=models.UniqueConstraint(
                fields=("settlement", "challenge_member"), name="uniq_settlement_member"
            ),
        ),
    ]
